baseURL = "https://urjatrust.netlify.app/"
languageCode = "en-us"
theme = "welfare"
title = "Urja"
[[menu.nav]]
name = "DONATE"
url = "/get_involved/donate/"
weight = 7
[[menu.nav]]
name = "Home"
url = "/"
weight = 1
