baseURL = "http://example.org/"
languageCode = "en-us"
title = "Urja"
theme = "welfare"

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.nav]]
    name = "Causes"
    url = "/causes/"
    weight = 3
  [[menu.nav]]
    name = "Donate"
    url = "/donate/"
    weight = 4
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
