baseURL = "https://urjatrust.netlify.app/"
languageCode = "en-us"
theme = "welfare"
title = "Urja"
[[menu.nav]]
name = "DONATE"
url = "/donate/"
weight = 6
[[menu.nav]]
name = "Home"
url = "/"
weight = 1
