baseURL = "https://urja.com/"
languageCode = "en-us"
theme = "welfare"
title = "Urja"
[[menu.nav]]
name = "RSS"
url = "/index.xml"
weight = 5
[[menu.nav]]
name = "Donate"
url = "/donate/"
weight = 4
[[menu.nav]]
name = "Causes"
url = "/causes/"
weight = 3
[[menu.nav]]
name = "About"
url = "/about/"
weight = 2
[[menu.nav]]
name = "Home"
url = "/"
weight = 1
