---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: document
  path: content/about/_index.md
  label: About
  match: "**/*"
- type: heading
  label: Pages
- type: document
  path: data/home.yml
  label: Home Page
- type: directory
  path: content/blog
  label: Blog
  create: documents
  match: "**/*"
- type: directory
  path: content/events
  label: Events
  create: documents
  match: "**/*"
- type: heading
  label: Miscellaneous
- type: directory
  path: data
  label: Data Files
  create: documents
  match: "**/*"
  new_doc_ext: yml
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.71.1
