---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: data/home.yml
  label: Home Page
- type: directory
  path: content/about
  label: About
  create: documents
  match: "**/*"
  templates:
  - about-page
- type: directory
  path: content/approach
  label: Approach
  create: documents
  match: "**/*"
  templates:
  - approach
- type: directory
  path: content/events
  label: Events
  create: documents
  match: "**/*"
  templates:
  - taxonomy
  - events-page
- type: directory
  path: content/get_involved
  label: Get Involved
  create: all
  match: "**/*"
  templates:
  - taxonomy
  - get-involved-page
- type: directory
  path: content/blog
  label: Blog
  create: documents
  match: "**/*"
  templates:
  - taxonomy
  - blog-post-page
- type: heading
  label: Miscellaneous
- type: document
  path: data/counter.yml
  label: Counter
- type: document
  path: data/footer.yml
  label: Footer
- type: document
  path: content/categories/_index.md
  label: Categories
- type: document
  path: content/tags/_index.md
  label: Tags
upload_dir: static/images/uploads
public_path: "/images/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.71.1
